version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule: &id001
    interval: weekly
    day: monday
    time: 06:00
    timezone: Europe/Zurich
  open-pull-requests-limit: 3
  groups: &id002
    minor-and-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    security-minor-and-patch:
      applies-to: security-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: swift
  directory: /
  schedule: *id001
  open-pull-requests-limit: 3
  groups: *id002
